services:
  cloudflare-error-page:
    image: ghcr.io/fa0311/cloudflare-error-page-docker:latest
    volumes:
      - ./params.json:/app/params.json:ro
    ports:
      - "5050:5000"
    environment:
      - HOST=0.0.0.0
      - PORT=5000
